{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"nuke_display"},{"kind":"text","text":"("},{"kind":"externalParam","text":"image"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.github.kean.Nuke\/documentation\/Nuke\/PlatformImage","preciseIdentifier":"s:4Nuke13PlatformImagea","text":"PlatformImage"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"data"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/nuke\/nuke_imagedisplaying\/nuke_display(image:data:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/nuke\/nuke_imagedisplaying\/nuke_display(image:data:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.github.kean.Nuke\/documentation\/Nuke\/Nuke_ImageDisplaying\/nuke_display(image:data:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Display a given image."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"nuke_displayWithImage:data:"}],"role":"symbol","title":"nuke_display(image:data:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"nuke_display"},{"kind":"text","text":"("},{"kind":"externalParam","text":"image"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PlatformImage","preciseIdentifier":"s:4Nuke13PlatformImagea"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"data"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"?)"}],"symbolKind":"method","externalID":"c:@M@Nuke@objc(pl)Nuke_ImageDisplaying(im)nuke_displayWithImage:data:","required":true,"modules":[{"name":"Nuke"}]},"hierarchy":{"paths":[["doc:\/\/com.github.kean.Nuke\/documentation\/Nuke","doc:\/\/com.github.kean.Nuke\/documentation\/Nuke\/Nuke_ImageDisplaying"]]},"references":{"doc://com.github.kean.Nuke/documentation/Nuke":{"role":"collection","title":"Nuke","abstract":[],"identifier":"doc:\/\/com.github.kean.Nuke\/documentation\/Nuke","kind":"symbol","type":"topic","url":"\/documentation\/nuke"},"doc://com.github.kean.Nuke/documentation/Nuke/Nuke_ImageDisplaying":{"role":"symbol","title":"Nuke_ImageDisplaying","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Nuke_ImageDisplaying"}],"abstract":[{"type":"text","text":"Displays images. Add the conformance to this protocol to your views to make"},{"type":"text","text":" "},{"type":"text","text":"them compatible with Nuke image loading extensions."}],"identifier":"doc:\/\/com.github.kean.Nuke\/documentation\/Nuke\/Nuke_ImageDisplaying","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Nuke_ImageDisplaying"}],"url":"\/documentation\/nuke\/nuke_imagedisplaying"},"doc://com.github.kean.Nuke/documentation/Nuke/Nuke_ImageDisplaying/nuke_display(image:data:)":{"navigatorTitle":[{"kind":"identifier","text":"nuke_displayWithImage:data:"}],"role":"symbol","title":"nuke_display(image:data:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"nuke_display"},{"kind":"text","text":"("},{"kind":"externalParam","text":"image"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PlatformImage","preciseIdentifier":"s:4Nuke13PlatformImagea"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"data"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Display a given image."}],"identifier":"doc:\/\/com.github.kean.Nuke\/documentation\/Nuke\/Nuke_ImageDisplaying\/nuke_display(image:data:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/nuke\/nuke_imagedisplaying\/nuke_display(image:data:)"},"doc://com.github.kean.Nuke/documentation/Nuke/PlatformImage":{"role":"symbol","title":"PlatformImage","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlatformImage"}],"abstract":[{"type":"text","text":"Alias for "},{"type":"codeVoice","code":"UIImage"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.github.kean.Nuke\/documentation\/Nuke\/PlatformImage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PlatformImage"}],"url":"\/documentation\/nuke\/platformimage"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"nuke_displayWithImage:data:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"nuke_displayWithImage:data:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"nuke_displayWithImage:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"image"},{"kind":"text","text":" "},{"kind":"identifier","text":"data:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSData","preciseIdentifier":"c:objc(cs)NSData"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"data"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.github.kean.Nuke~1documentation~1Nuke~1Nuke_ImageDisplaying\/title","value":"Nuke_ImageDisplaying"},{"op":"replace","path":"\/references\/doc:~1~1com.github.kean.Nuke~1documentation~1Nuke~1Nuke_ImageDisplaying\/fragments","value":[{"kind":"identifier","text":"Nuke_ImageDisplaying"}]},{"op":"replace","path":"\/references\/doc:~1~1com.github.kean.Nuke~1documentation~1Nuke~1Nuke_ImageDisplaying~1nuke_display(image:data:)\/title","value":"nuke_displayWithImage:data:"},{"op":"replace","path":"\/references\/doc:~1~1com.github.kean.Nuke~1documentation~1Nuke~1Nuke_ImageDisplaying~1nuke_display(image:data:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"nuke_displayWithImage:data:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}