{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Nuke_ImageDisplaying"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The protocol is defined as "},{"type":"codeVoice","code":"@objc"},{"type":"text","text":" to make it possible to override its"},{"type":"text","text":" "},{"type":"text","text":"methods in extensions (e.g. you can override "},{"type":"codeVoice","code":"nuke_display(image:data:)"},{"type":"text","text":" in"},{"type":"text","text":" "},{"type":"codeVoice","code":"UIImageView"},{"type":"text","text":" subclass like `Gifu.ImageView)."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"The protocol and its methods have prefixes to make sure they don’t clash"},{"type":"text","text":" "},{"type":"text","text":"with other similar methods and protocol in Objective-C runtime."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/nuke\/nuke_imagedisplaying"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/nuke\/nuke_imagedisplaying"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.github.kean.Nuke\/documentation\/Nuke\/Nuke_ImageDisplaying","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Displays images. Add the conformance to this protocol to your views to make"},{"type":"text","text":" "},{"type":"text","text":"them compatible with Nuke image loading extensions."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Nuke_ImageDisplaying"}],"title":"Nuke_ImageDisplaying","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:@M@Nuke@objc(pl)Nuke_ImageDisplaying","modules":[{"name":"Nuke"}],"navigatorTitle":[{"kind":"identifier","text":"Nuke_ImageDisplaying"}]},"hierarchy":{"paths":[["doc:\/\/com.github.kean.Nuke\/documentation\/Nuke"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.github.kean.Nuke\/documentation\/Nuke\/Nuke_ImageDisplaying\/nuke_display(image:data:)"]}],"references":{"doc://com.github.kean.Nuke/documentation/Nuke":{"role":"collection","title":"Nuke","abstract":[],"identifier":"doc:\/\/com.github.kean.Nuke\/documentation\/Nuke","kind":"symbol","type":"topic","url":"\/documentation\/nuke"},"doc://com.github.kean.Nuke/documentation/Nuke/Nuke_ImageDisplaying/nuke_display(image:data:)":{"navigatorTitle":[{"kind":"identifier","text":"nuke_displayWithImage:data:"}],"role":"symbol","title":"nuke_display(image:data:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"nuke_display"},{"kind":"text","text":"("},{"kind":"externalParam","text":"image"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PlatformImage","preciseIdentifier":"s:4Nuke13PlatformImagea"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"data"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Display a given image."}],"identifier":"doc:\/\/com.github.kean.Nuke\/documentation\/Nuke\/Nuke_ImageDisplaying\/nuke_display(image:data:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/nuke\/nuke_imagedisplaying\/nuke_display(image:data:)"},"doc://com.github.kean.Nuke/documentation/Nuke/Nuke_ImageDisplaying":{"role":"symbol","title":"Nuke_ImageDisplaying","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Nuke_ImageDisplaying"}],"abstract":[{"type":"text","text":"Displays images. Add the conformance to this protocol to your views to make"},{"type":"text","text":" "},{"type":"text","text":"them compatible with Nuke image loading extensions."}],"identifier":"doc:\/\/com.github.kean.Nuke\/documentation\/Nuke\/Nuke_ImageDisplaying","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Nuke_ImageDisplaying"}],"url":"\/documentation\/nuke\/nuke_imagedisplaying"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"Nuke_ImageDisplaying"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"Nuke_ImageDisplaying"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"Nuke_ImageDisplaying"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.github.kean.Nuke\/documentation\/Nuke\/Nuke_ImageDisplaying\/nuke_display(image:data:)"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Nuke_ImageDisplaying"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.github.kean.Nuke~1documentation~1Nuke~1Nuke_ImageDisplaying~1nuke_display(image:data:)\/title","value":"nuke_displayWithImage:data:"},{"op":"replace","path":"\/references\/doc:~1~1com.github.kean.Nuke~1documentation~1Nuke~1Nuke_ImageDisplaying~1nuke_display(image:data:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"nuke_displayWithImage:data:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.github.kean.Nuke~1documentation~1Nuke~1Nuke_ImageDisplaying\/title","value":"Nuke_ImageDisplaying"},{"op":"replace","path":"\/references\/doc:~1~1com.github.kean.Nuke~1documentation~1Nuke~1Nuke_ImageDisplaying\/fragments","value":[{"kind":"identifier","text":"Nuke_ImageDisplaying"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}